const CONFIG = {
  introTitle: "Anh có lời muốn nói muốn gửi đến Châu Linh 😘😘",
  introDesc: ` Lần này anh may mắn  đã tìm được đúng cô gái thiên bình t10 thông minh, xinh gái được ví như bạch nguyệt quang của đời anh rùi `,
  btnIntro: "Đặc biệt hơn ở phía sau nè ",
  title: " Anh thực sự rất thích em và yêu em  😙",
  desc: "Châu Linh ơi, em có thể cho anh 1 cơ hội được làm người yêu em đồng hành cùng em  nka 😘😘   ",
  btnYes: "Em đồng ý  <33",
  btnNo: "Không ạ :3",
  question: "Giữa hàng vạn người  em là cô gái  đặc biệt nhất đối với anh  <3",
  btnReply: "Gửi cho anh <3",
  reply: "dạ ",
  mess: "Yêu em nhiều lém  😘😘",
  messDesc: " Anh  hẹn em 1 buổi ở ngoài tết nhé  công chúa .Yêu em!  ",
  btnAccept: "Okiiiii lun <3",
  messLink: "https://manhhung1303.github.io/codeheart/",
};
